### ISSUE TITLE
Application unable to see all files

### ISSUE THREAD

**Issue by ieris19** [flathub/com.gluonhq.SceneBuilder#20]
I am reporting this issue here, because it is an issue with the flatpak implementation specifically which I understand as per [scenebuilder#559.](https://github.com/gluonhq/scenebuilder/issues/559) is not officially maintained.

I orginally installed the flatpak application's flatpak through GNOME software and to my surprise, couldn't open my project from an external drive.

This has sent me down a rabbit hole researching this issue, which brings me here to report this, in hopes of someone knowing where this issue needs to be addressed.

I started reading in [flatpak#2713](https://github.com/flatpak/flatpak/issues/2713) where the conclusion is that the application needs to be the one implementing the portal integration. I then logically asked how would one do this in Java, and found this issue [xdg-desktop-portal#519](https://github.com/flatpak/xdg-desktop-portal/issues/519) (4yo discussion) that brings up that it should be the JDK that implements this functionality, which leads me to a [org.freedesktop.Sdk.Extension.openjdk11#15](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/issues/15) this last one is about Swing specifically and the [last comment](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/issues/15#issuecomment-924722172) claims that since Java SWT uses GTK, it simply inherits GTK's compatibility with portals.

After poking around the JDK bug-tracker I found "https://bugs.openjdk.org/browse/JDK-8087516" which signals that JavaFx also runs on GTK (this was MANY years ago) so I wonder what the problem I'm facing here is.

Thank you so much for your time

**Comment by ghazyami** [comment]
Just to understand more, you are only talking about portals to dynamically open files that the flatpak does not have explicit permissions to acess right, in another words, if you mount your external drive to say `/mnt/my-drive` and give the flatpak permission to this path `/mnt/my-drive`  via flatseal for example, you are able to access  your files, correct?

**Comment by ieris19** [comment]
Yes, I am not fully familiar with Flatpak packaging as I am relatively new to Linux as a whole, but given the fact that Scene Builder managed to read files available in the home directory but wouldn't even show directiories such as `/mnt` or `/media` I assume granting it permission through flatseal (which if I am not mistaken is just an application that manages flatpak sandbox permission right?) it should be able to see the files, since the latest RPM from Gluon seems to be working just fine on my computer

**Comment by ghazyami** [comment]
Correct, giving the flatpak permission to access where your files are should work.

Flatseal is indeed just an application to manage permissions in a gui form.
https://flathub.org/apps/com.github.tchx84.Flatseal

After selecting scenebuilder then under the filesystem section you can add a path to your files

**Comment by ieris19** [comment]
I guess then it's working as intended? Will close this issue and use Flatseal then
