### ISSUE TITLE
Suggestion- Include parameter to use Open With 

### ISSUE THREAD

**Issue by moacirrf** [flathub/com.gluonhq.SceneBuilder#7]
Hi,
Thanks to maintain this package.

Maybe is interesting include a parameter on manifest, to make it possible to use the "Open With" option to open an fxml.
![image](https://user-images.githubusercontent.com/950706/216164253-b46f75be-1fe5-41ca-9f2d-52521b1bce90.png)

thanks

**Comment by ghazyami** [comment]
Thank you for pointing that out, done on #8.
Please test and feel free to close the ticket if it's working like expected

**Comment by moacirrf** [comment]
It' works.
Thanks
